import { afterEach, describe, expect, it } from "vitest";
import { devOffline, resetEnvCache } from "../env.js";
import { devOfflineAuth, devUserId } from "../lib/auth/dev-offline.js";
import { getAuth } from "../lib/auth/supabase.js";
import { createDevDb } from "../db/dev-offline.js";
import { resetDeps } from "../lib/deps.js";
import * as schema from "../db/schema.js";

const ENV_KEYS = ["DEV_OFFLINE", "SUPABASE_URL", "VERCEL"] as const;
const saved = new Map<string, string | undefined>();

function setEnv(key: string, value: string | undefined) {
  if (!saved.has(key)) saved.set(key, process.env[key]);
  if (value === undefined) delete process.env[key];
  else process.env[key] = value;
  resetEnvCache();
}

afterEach(() => {
  for (const [key, value] of saved) {
    if (value === undefined) delete process.env[key];
    else process.env[key] = value;
  }
  saved.clear();
  resetEnvCache();
  resetDeps();
});

describe("devOffline gate", () => {
  it("is off by default and on only with DEV_OFFLINE=1", () => {
    for (const key of ENV_KEYS) setEnv(key, undefined);
    expect(devOffline()).toBe(false);
    setEnv("DEV_OFFLINE", "1");
    expect(devOffline()).toBe(true);
  });

  it("never activates on Vercel", () => {
    setEnv("DEV_OFFLINE", "1");
    setEnv("VERCEL", "1");
    expect(devOffline()).toBe(false);
  });

  it("selects the offline adapter only when Supabase is absent", () => {
    setEnv("DEV_OFFLINE", "1");
    setEnv("SUPABASE_URL", undefined);
    setEnv("VERCEL", undefined);
    expect(getAuth()).toBe(devOfflineAuth);
    setEnv("SUPABASE_URL", "https://example.supabase.co");
    expect(getAuth()).not.toBe(devOfflineAuth);
  });
});

describe("devOfflineAuth", () => {
  it("logs in with any email and password, and the cookie round-trips", async () => {
    const result = await devOfflineAuth.signInWithPassword({
      email: "demo@example.com",
      password: "anything",
    });
    if (!result.ok) throw new Error(result.error);
    expect(result.user.email).toBe("demo@example.com");
    expect(result.user.id).toMatch(
      /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-8[0-9a-f]{3}-[0-9a-f]{12}$/,
    );
    const user = await devOfflineAuth.userFromCookie(result.cookie);
    expect(user).toEqual(result.user);
  });

  it("is deterministic: same email, same user id", () => {
    expect(devUserId("a@b.co")).toBe(devUserId("A@B.CO"));
    expect(devUserId("a@b.co")).not.toBe(devUserId("c@d.co"));
  });

  it("rejects empty passwords and junk cookies", async () => {
    const bad = await devOfflineAuth.signInWithPassword({
      email: "demo@example.com",
      password: "",
    });
    expect(bad.ok).toBe(false);
    expect(await devOfflineAuth.userFromCookie(null)).toBeNull();
    expect(
      await devOfflineAuth.userFromCookie("sb-access-token=not-a-dev-token"),
    ).toBeNull();
  });

  it("refuses magic links and OAuth with a pointer to password login", async () => {
    await expect(
      devOfflineAuth.sendMagicLink({
        email: "demo@example.com",
        emailRedirectTo: "http://localhost:3000/auth/callback",
      }),
    ).rejects.toThrow(/password/i);
    await expect(
      devOfflineAuth.startOAuth({
        provider: "google",
        redirectTo: "http://localhost:3000/auth/callback",
      }),
    ).rejects.toThrow(/password/i);
  });
});

describe("createDevDb", () => {
  it("serves queries only after the schema setup (no first-request race)", async () => {
    const db = createDevDb();
    // Immediate query: must wait for the schema exec, then see the accounts table.
    const rows = await db.select().from(schema.accounts);
    expect(rows).toEqual([]);
  });
});

describe("dev schema snapshot", () => {
  it("src/db/dev-schema.ts matches src/db/schema.ts (UPDATE_DEV_SCHEMA=1 to regenerate)", async () => {
    // drizzle-kit's CLI machinery is unsafe inside a long-lived server, so the
    // runtime executes this committed snapshot instead. This test is the
    // generator and the drift guard in one.
    const { createRequire } = await import("node:module");
    const { PGlite } = await import("@electric-sql/pglite");
    const { drizzle } = await import("drizzle-orm/pglite");
    const require = createRequire(import.meta.url);
    const { pushSchema } = require("drizzle-kit/api") as
      typeof import("drizzle-kit/api");
    const db = drizzle(new PGlite(), { schema });
    const { statementsToExecute } = await pushSchema(
      schema,
      db as unknown as Parameters<typeof pushSchema>[1],
    );
    const sql = `${statementsToExecute.join(";\n")};\n`;

    const { fileURLToPath } = await import("node:url");
    const path = fileURLToPath(
      new URL("../db/dev-schema.ts", import.meta.url),
    );
    const banner =
      "// Generated by src/test/dev-offline.test.ts. Do not edit.\n// Regenerate after schema changes: UPDATE_DEV_SCHEMA=1 npx vitest run src/test/dev-offline.test.ts\n";
    const contents = `${banner}export const DEV_SCHEMA_SQL = ${JSON.stringify(sql)};\n`;

    const { readFileSync, writeFileSync } = await import("node:fs");
    if (process.env.UPDATE_DEV_SCHEMA === "1") {
      writeFileSync(path, contents);
      return;
    }
    expect(readFileSync(path, "utf8")).toBe(contents);
  });
});
